# learning params
learning_rate: 0.001
device: "cuda"
batch_size: 16
num_epochs: 3
num_workers: 2
pin_memory: True
load_model: False

random_state: 23572

# data params
img_size: [768, 768]
test_path: "./test_v2"
train_path: "./train_v2"
masks_path: "./train_ship_segmentations_v2.csv"
